// ********RoostGPT********
// Test generated by RoostGPT for test nodejs-test-1 using AI Type Open AI and AI Model gpt-4



// ********RoostGPT********
const request = require('supertest');
const express = require('express');
const app = express();

app.get('/test', function(req, res) {
  res.status(200).json({name: 'test'});
});

describe('Test the root path', () => {
  test('It should response the GET method', () => {
    return request(app).get("/test").then(response => {
      expect(response.statusCode).toBe(200);
      expect(response.body).toEqual({name: 'test'});
    });
  });
});
