// ********RoostGPT********
// Test generated by RoostGPT for test nodejs-test-1 using AI Type Open AI and AI Model gpt-4



// ********RoostGPT********
const request = require('supertest');
const app = require('./app');

describe('Server Tests', () => {
  let server;

  beforeAll(done => {
    server = app.listen(3000, () => {
      done();
    });
  });

  afterAll(done => {
    server.close(done);
  });

  test('should start server without error', async () => {
    const res = await request(server).get('/');
    expect(res.statusCode).toEqual(200);
  });

  test('should handle server error', async () => {
    const res = await request(server).get('/error-route');
    expect(res.statusCode).toEqual(500);
  });
});
