// Test regenerated by RoostGPT for test nodejs-test-1 using AI Type Open AI and AI Model gpt-4

// Make sure to install 'supertest' before running the test
// You can install it using npm (Node Package Manager) by running 'npm install supertest'
const request = require('supertest');
const express = require('express');
const app = require('./app');

describe('POST /send', () => {
  let data = {
    name: 'John Doe',
    company: 'ABC',
    email: 'john.doe@gmail.com',
    phone: '1234567890',
    message: 'Hello World'
  };

  beforeAll(() => {
    app.post('/send', (req, res) => {
      res.status(200).json(req.body);
    });
  });

  test('responds with sent message', async () => {
    const response = await request(app)
      .post('/send')
      .send(data);
    expect(response.statusCode).toBe(200);
    expect(response.body).toEqual(data);
  });

  test('responds with error message when data is missing', async () => {
    const response = await request(app)
      .post('/send')
      .send({});
    expect(response.statusCode).toBe(500);
    expect(response.body).toHaveProperty('error');
  });
});
